/**********************************************************************************************************************
 * \file SCR_Port_Pin_Config.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "registers.h"
#include "scr_header_files.h"
#include "SCR_Macros.h"
#include "SCR_TypesReg.h"



//#define
//#define
///*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define  SCR_Port0_Index_00     0   /**< \brief Port 00 */
#define  SCR_Port1_Index_01     1   /**< \brief Port 01 */
#define  SCR_Port2_Index_02     2   /**< \brief Port 02 */
#define  SCR_Port3_Index_03     3    /**< \brief Port 03 */

#define  SCR_Port_PinIndex_0    0  /**< \brief Pin 0 */
#define  SCR_Port_PinIndex_1    1  /**< \brief Pin 1 */
#define  SCR_Port_PinIndex_2    2  /**< \brief Pin 2 */
#define  SCR_Port_PinIndex_3    3  /**< \brief Pin 3 */
#define  SCR_Port_PinIndex_4    4  /**< \brief Pin 4 */
#define  SCR_Port_PinIndex_5    5  /**< \brief Pin 5 */
#define  SCR_Port_PinIndex_6    6  /**< \brief Pin 6 */
#define  SCR_Port_PinIndex_7    7  /**< \brief Pin 7 */

#define  SCR_IoControl_input_tristate        0x0    /**< \brief No input pull device connected, tri-state mode */
#define  SCR_IoControl_output_pushpullGpio   0x10   /**< \brief Push pull general purpose output */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void IfxScrPort_configurePortControl(unsigned char port, unsigned char pinIndex,unsigned char controlValue);
void SCR_Port_EnablePortPad(unsigned char port, unsigned char pinIndex);
void SCR_GPIO_EnablePortPad(unsigned int port);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/**********************************************************************************************************************/
void gpio_config(void){


    IfxScrPort_configurePortControl(SCR_Port0_Index_00,SCR_Port_PinIndex_2 ,SCR_IoControl_output_pushpullGpio );
    IfxScrPort_configurePortControl(SCR_Port0_Index_00,SCR_Port_PinIndex_3 ,SCR_IoControl_output_pushpullGpio );
    IfxScrPort_configurePortControl(SCR_Port0_Index_00,SCR_Port_PinIndex_4 ,SCR_IoControl_output_pushpullGpio );

}


void IfxScrPort_configurePortControl(unsigned char port, unsigned char pinIndex,unsigned char controlValue)
{
    SCR_IO_PAGE = 1;        //Switch to page 1

    SCR_IO_PAGE = SCR_IO_PAGE2;        //Switch to page 2
           SCR_P00_PDISC = 0x00;
           SCR_P01_PDISC = 0x00;
    if (port == SCR_Port0_Index_00)
    {
        if(pinIndex == SCR_Port_PinIndex_2){ SCR_P00_IOCR2 = controlValue;   }
        else if(pinIndex == SCR_Port_PinIndex_3){ SCR_P00_IOCR3 = controlValue;   }
        else if(pinIndex == SCR_Port_PinIndex_4){   SCR_P00_IOCR4 = controlValue;  }
        else {}

//        switch (pinIndex)
//        {
//        case SCR_Port_PinIndex_0:
//            SCR_P00_IOCR0 = controlValue;
//            break;
//        case SCR_Port_PinIndex_1:
//            SCR_P00_IOCR1 = controlValue;
//            break;
//        case SCR_Port_PinIndex_2:
//            SCR_P00_IOCR2 = controlValue;
//            break;
//        case SCR_Port_PinIndex_3:
//            SCR_P00_IOCR3 = controlValue;
//            break;
//        case SCR_Port_PinIndex_4:
//            SCR_P00_IOCR4 = controlValue;
//            break;
//        case SCR_Port_PinIndex_5:
//            SCR_P00_IOCR5 = controlValue;
//            break;
//        case SCR_Port_PinIndex_6:
//            SCR_P00_IOCR6 = controlValue;
//            break;
//        case SCR_Port_PinIndex_7:
//            SCR_P00_IOCR7 = controlValue;
//            break;
//        default:
//            /* Invalid Pin selected */
//            break;
//        }
    }

    else if (port == SCR_Port1_Index_01)
        {
            switch (pinIndex)
            {
            case SCR_Port_PinIndex_0:
                SCR_P00_IOCR0 = controlValue;
                break;
            case SCR_Port_PinIndex_1:
                SCR_P00_IOCR1 = controlValue;
                break;
            case SCR_Port_PinIndex_2:
                SCR_P00_IOCR2 = controlValue;
                break;
            case SCR_Port_PinIndex_3:
                SCR_P00_IOCR3 = controlValue;
                break;
            case SCR_Port_PinIndex_4:
                SCR_P00_IOCR4 = controlValue;
                break;
            case SCR_Port_PinIndex_5:
                SCR_P00_IOCR5 = controlValue;
                break;
            case SCR_Port_PinIndex_6:
                SCR_P00_IOCR6 = controlValue;
                break;
            case SCR_Port_PinIndex_7:
                SCR_P00_IOCR7 = controlValue;
                break;
            default:
                /* Invalid Pin selected */
                break;
            }
        }
    else
        {  /* dummy else*/ }

}

void SCR_Port_EnablePortPad(unsigned char port, unsigned char pinIndex)
{
    SCR_IO_PAGE = 2;

    if (port == SCR_Port0_Index_00)
    {
        SCR_P00_PDISC = 0x00;
    }
    if  (port == SCR_Port1_Index_01)
    {
        SCR_P01_PDISC = 0x00;
    }

}


void SCR_GPIO_EnablePortPad(unsigned int port)
{
    SCR_IO_PAGE = 2;

    if (port == SCR_Port0_Index_00)
    {
        SCR_P00_PDISC = 0x00;
    }
    if  (port == SCR_Port1_Index_01)
    {
        SCR_P01_PDISC = 0x00;
    }

}






