/**********************************************************************************************************************
 * \file main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "registers.h"
#include "scr_header_files.h"
#include "SCR_Macros.h"
#include "SCR_TypesReg.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define     SCR_IO_PAGE0    0
#define     SCR_IO_PAGE1    1
#define     SCR_IO_PAGE2    2
#define     CLEAR_BIT_5_IN_IR_CON0          5
#define     CLEAR_BIT_3_IN_T01_TCON         3
#define     CLEAR_BIT_2_IN_IR_CON0          2
#define     Bitmaske_pin_6                  0x40

//   #define MEM_SEGMENT_SHARED_DATA         0x1F00
// #define Scr_Shared_Data  (*(volatile SCR_SHARED_DATA_TYPE*) 0x1F00)
// __xdata __at(0x1F00)  uint16 Data ;
 /*********************************************************************************************************************/
 /*-------------------------------------------------Global variables--------------------------------------------------*/
 /*********************************************************************************************************************/


 volatile unsigned char Start_PWM_Duty_Dycle_Calculating  = 0;
 volatile unsigned char Check_Pin_Stat = 0;
 volatile unsigned char Edge_Detection = 0;

 volatile unsigned char rising_edge = 0;
 /*********************************************************************************************************************/
 /*------------------------------------------------Function Prototypes------------------------------------------------*/
 /*********************************************************************************************************************/
void delay(void);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void main()
{

    volatile unsigned char ADC_Stat = 0;
    volatile unsigned long Capture_Value_sum = 0;
    volatile unsigned long temp = 0;
    volatile unsigned char Duty_Cycle = 0;
    /* SCU module configurations*/
    SCR_SCU_PAGE = 1;       //Switch to page 1
    SCR_SCU_PMCON1 = 0x59;  //OCDS, T2CCU0, RTC and WCAN enabled
    SCR_SCU_PAGE = 0;       //Switch to page 0
    SCR_SCRINTEXCHG = 0xA0;
    SCR_SCU_PAGE = 1;       //Switch to page 0
    // Enable global interrupt RMAP: X, PAGE: X
    SCR_IEN0 |= (1 << 7) ; // enable global interrupt Set bit 7
    gpio_init();
    SCR_IR_Select_External_Interrupt_Line();
    SCR_IR_Select_Edge_Mode();
    SCR_IR_Enable_Interrupt_Node();
    SCR_Select_Interrupt_Priority();
     //SCR_Timer_2_Basic_Operations();
    SCR_CCT_Timer_Basic_Operation();
    // SCR_CCU_Capture_Mode_1_Config();
    SCR_CCU_Capture_Mode_0();
    while(1)
    {

        if(Start_PWM_Duty_Dycle_Calculating == 0)
        {
            SCR_IO_PAGE = SCR_IO_PAGE0;
                if(Edge_Detection == 1) { SCR_P00_OUT |= (1 << 3) ; Falling_Edge = 0; Reset_CCT_Timer(); }// reset cct

                if(Edge_Detection == 2){

                        SCR_P00_OUT |= (1 << 5) ; CCT_Read_PWM_OnTime(); //falling Capture on time
                    }


                if(Edge_Detection == 3) {

                        SCR_P00_OUT |= (1 << 4) ;  CCT_Read_PWM_OffTime();  // capture sume time rising EDGE
                    }


                if(Edge_Detection == 4) // FALLING
                     {
                        Rising_Edge = 0;
                        Falling_Edge = 0;
                         SCR_P00_OUT &= ~ (1 << 3);
                         SCR_P00_OUT &= ~ (1 << 5);
                         SCR_P00_OUT &= ~ (1 << 4);

                       //  Duty_Cycle_Calculator_Function();

                         }
        }







     //
    }
}

/*****************************************************************************************
 *
 *****************************************************************************************/
void delay(void)
{
    int i = 0;
    int j = 0;
    for( i = 0; i < 1000; i++){
        for(j = 0; j < 1000; j++){
        }
    }
}
/***************************************************************************************/
/***************************************************************************************/
/*  ISR Node 5  CCT timer */
void EXINT5IS_interrupt(void) __interrupt (5){
//    SCR_IO_PAGE = SCR_IO_PAGE0;
//    SCR_P00_OUT ^= (1 << 3) ;
//    SCR_T2CCU_PAGE = 1;
//    SCR_T2CCU_CCTCON &= ~(1 << 3) ;//bit pos 3 overflow flag
}
/***************************************************************************************/
/***************************************************************************************/
/*  ISR Node 8*/
void EXINT8IS_interrupt(void) __interrupt (8){

    rising_edge++;


    SCR_SCU_PAGE = 0;
    SCR_IR_CON0 &= ~(1 << 2);// Node 8 bit pos 2

}
/***************************************************************************************/
/***************************************************************************************/
/* ISR Node 9*/
void EXINT9IS_interrupt(void) __interrupt (9){
// man weis nicht ob dies variable bei steigen oder fallende um 1 erhöht wird, hier kommt die priority ovn diesem 2 Node im spiel.
    if(rising_edge >= 1){Edge_Detection++; }


/***********************************************************************************************************************************************************************************
 * achtung!! wenn 1 eterneal interrupt, der mit 2 node verbunden ist, und ein von diesem node für steigen und fallend flanken konfiguriert ist,
 *  wird der zählvariable im diesem node, die bei jede flanke ausgeführt wird, um 1 erhöht
 *  *************************************************************************************************************************************************************************/
    //SCU_PAGE=0
        SCR_SCU_PAGE = 0;
    SCR_IR_CON0 &= ~(1 << 3);// Node 9 bit pos 3
}
/*********************************************************************************************************************************/

/*********************************************************************************************************************************/

/*********************************************************************************************************************************/
