/**********************************************************************************************************************
 * \file scr_adc_init.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "registers.h"
#include "scr_header_files.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ADCENREQ                0
#define ADCENST                 0x02
#define ADCCHSEL                3
#define SOC                     7
#define EOCSAMPLE               0x40
#define VF                      0x20
#define ADCNORESULTORINVALID    0
#define ADCRESULTVALID          1

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
unsigned char SCR_ADC_IsSampling(void)
{
     SCR_SCU_PAGE = 0;
     return  (SCR_ADCOMP_CON & EOCSAMPLE);
}

/*Enable ADC and Trigger a Dummy Conversion  */
void SCR_ADC_EnableModulTriggerDumyConversion(void){
// SCU_PAGE = 0
    SCR_SCU_PAGE = 0;
    SCR_ADCOMP_CON |= (1 << ADCENREQ) ; // Enable ADC
    /* Wait for module to start */
    while (!(SCR_ADC_IsEnabled()))  {}
    // Trigger a dummy conversion to avoid wrong conversion
    SCR_ADCOMP_CON |= (1 << SOC);
    /* wait until dummy conversion is finished */
    while(!(SCR_ADC_IsSampling())){}
}

void SCR_ADC_DisableModule(void){
    SCR_SCU_PAGE = 0;
    SCR_ADCOMP_CON &= ~(1 << ADCENREQ) ; // Disable ADC
}

unsigned char SCR_ADC_IsEnabled(void){
    SCR_SCU_PAGE = 0;
    return(SCR_ADCOMP_CON & ADCENST);
}
unsigned char SCR_ADC_isReadyForNewConversion(void){
    SCR_SCU_PAGE = 0;
    return(SCR_ADCOMP_CON & VF);
}
void SCR_ADC_SelectChannel(SCR_ADC_Chanel_Select channel){
    SCR_SCU_PAGE = 0;
    SCR_ADCOMP_CON |= (channel << ADCCHSEL) ; // select ADC Chanel
}
void SCR_ADC_StartNewConversion(void){
    SCR_SCU_PAGE = 0;
    SCR_ADCOMP_CON |= (1 << SOC);
}
/* Is Conversion available and valid */
unsigned char SCR_ADC_IsResultValid(void)
{
     unsigned char return_char = ADCNORESULTORINVALID;

     SCR_SCU_PAGE = 0;
     if ((SCR_ADCOMP_CON & 0x60) == 0x60)//  in Bit 01100000  VF and EOCSAMPLE
        {
            return_char = ADCRESULTVALID;
        }
     return return_char;
}

unsigned char SCR_ADC_GetResult(void){

    unsigned char return_result=0;
    SCR_SCU_PAGE = 0;
    return_result = SCR_ADCOMP_RES;
    return return_result;
}
unsigned char SCR_ADC_StartNewConversionGetResult(void){

    unsigned char Result=0;
    unsigned char ADC_Timeout = 0;
    SCR_ADC_StartNewConversion();

    while ((SCR_ADC_IsResultValid() != ADCRESULTVALID) && (ADC_Timeout <= 10u))//5microsec Timeout
        {
            Result = SCR_ADC_GetResult();
            ADC_Timeout++;
        }
        return Result;
}
